version: "2"
services:
  mongo_service:
    container_name: mongo_int
    image: mongo
    volumes:
      - mongodata:/data/db
      - "./backend/Documents:/Documents"
    ports:
      - "27017:27017"
  backend_service:
    container_name: backend_int
    restart: always
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - "DB_URL=mongodb://192.168.99.100:27017"
    links:
      - mongo_service
    depends_on:
      - mongo_service
  businesslogic_service:
    container_name: businesslogic_int
    restart: always
    build:
      context: ./business_logic
    ports:
      - "8080:8080"
    environment:
      - "DB_IP=192.168.99.100"
      - "DB_PORT=27017"
    links:
      - mongo_service
    depends_on:
      - mongo_service
  webapp:
    container_name: webapp_int
    restart: always
    build:
      context: ./web-app
      args:
        - "env=dev"
    ports:
      - "4200:80"
    links:
      - businesslogic
    depends_on:
      - businesslogic

volumes:
  mongodata:
