@startuml context

top to bottom direction

actor user
actor :registered user: as reg

node application as app

user --> app: searches for\nsongs, albums and artists
reg --> app: tags songs, album and artists,\nadds friends and keeps favorites

cloud Spotify as spotify
cloud Youtube as youtube
cloud ApiSeeds as apiseeds

spotify --up-> app: provides information and\nlinks to listen
youtube --up-> app: provides links to listen
apiseeds --up-> app: provides lyrics for songs

@enduml
