@startuml Laufzeit_search
actor user
participant webapp
participant businesslogic
database mongo

user -> webapp : "Legend Has it"
webapp -> businesslogic : /search?term=Legend Has it
businesslogic -> mongo : search()
mongo -> businesslogic : result
businesslogic -> webapp : result
webapp -> user : show list with results

@enduml