@startuml


class AppcomponentView {
}

class LogincomponentView {
}
class RegistercomponentView {
}
class SongitemView {
}



AppcomponentView <|- LogincomponentView
AppcomponentView <|- RegistercomponentView
AppcomponentView <|- SongitemView


@enduml
